sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_install:
  - docker pull mongo:3.6
  - docker run --name mongodb_test -d -p 27017:27017 mongo:3.6
  - docker ps

install:
  - npm install mocha
  - npm install chai
  - npm install supertest
  - npm install --production
  - npm ls